export const FETCH_AVAILABLE_NODES_REQUEST = 'FETCH_AVAILABLE_NODES_REQUEST';
export const FETCH_AVAILABLE_NODES_SUCCESS = 'FETCH_AVAILABLE_NODES_SUCCESS';
export const FETCH_AVAILABLE_NODES_FAILURE = 'FETCH_AVAILABLE_NODES_FAILURE';
