export const FETCH_AVAILABLE_NODES_REQUEST = 'FETCH_AVAILABLE_NODES_REQUEST';
export const FETCH_AVAILABLE_NODES_SUCCESS = 'FETCH_AVAILABLE_NODES_SUCCESS';
export const FETCH_AVAILABLE_NODES_FAILURE = 'FETCH_AVAILABLE_NODES_FAILURE';

export const FETCH_MY_DEVICES_REQUEST = 'FETCH_MY_DEVICES_REQUEST';
export const FETCH_MY_DEVICES_SUCCESS = 'FETCH_MY_DEVICES_SUCCESS';
export const FETCH_MY_DEVICES_FAILURE = 'FETCH_MY_DEVICES_FAILURE';

export const FETCH_CONNECTOR_DETAILS_REQUEST = 'FETCH_CONNECTOR_DETAILS_REQUEST';
export const FETCH_CONNECTOR_DETAILS_SUCCESS = 'FETCH_CONNECTOR_DETAILS_SUCCESS';
export const FETCH_CONNECTOR_DETAILS_FAILURE = 'FETCH_CONNECTOR_DETAILS_FAILURE';

export const CREATE_CONNECTOR_REQUEST = 'CREATE_CONNECTOR_REQUEST';
export const CREATE_CONNECTOR_SUCCESS = 'CREATE_CONNECTOR_SUCCESS';
export const CREATE_CONNECTOR_FAILURE = 'CREATE_CONNECTOR_FAILURE';

export const SELECT_VERSION = 'SELECT_VERSION';
